README.md
pom.xml
src/main/scala/za/co/absa/commons/spark/SchemaUtils.scala
src/main/scala/za/co/absa/commons/spark/SparkTestBase.scala
src/test/scala/za/co/absa/commons/spark/SchemaUtilsSpec.scala

Not a clue who to add. Hope I did not forget anyone.

Add schema utils for comparison and diff

---

README.md
src/main/scala/za/co/absa/commons/version/Version.scala
src/test/scala/za/co/absa/commons/version/SemanticVersionSpec.scala
src/test/scala/za/co/absa/commons/version/SimpleVersionSpec.scala

commons #11 Version's missing a human readable toString or equivalent

---

README.md
src/main/scala/za/co/absa/commons/version/Version.scala
src/main/scala/za/co/absa/commons/version/impl/SemVer20Impl.scala
src/test/scala/za/co/absa/commons/version/SemanticVersionSpec.scala

commons #13 Version: add SemVer specific methods

---

src/main/scala/za/co/absa/commons/spark/SchemaUtils.scala
src/test/scala/za/co/absa/commons/spark/SchemaUtilsSpec.scala

- add isSubset to see if one schema is a subset of the other
- add alignSchema with option of passing in List[Column]

Enhance SchemaUtils

---

src/main/scala/za/co/absa/commons/lang/converters.scala
src/test/scala/za/co/absa/commons/lang/CachingConverterSpec.scala

commons #29 Caching Converter: support custom keys

---

README.md
src/main/scala/za/co/absa/commons/reflect/EnumerationMacros.scala
src/test/scala/za/co/absa/commons/reflect/EnumerationMacrosSpec.scala

commons #32 EnumerationMacros: get all instances of a sealed trait

---

src/main/scala/za/co/absa/commons/reflect/ReflectionUtils.scala
src/test/scala/za/co/absa/commons/reflect/ReflectionUtilsSpec.scala

commons #42 ReflectionUtils: java.lang.IndexOutOfBoundsException: 0

---

pom.xml

commons #52 A wrong java version is used for running unit-tests

---

src/main/scala/za/co/absa/commons/error/ErrorRef.scala
src/main/scala/za/co/absa/commons/error/ErrorRefFactory.scala
src/test/scala/za/co/absa/commons/error/ErrorRefFactorySpec.scala

commons #58 Client/Server error logging segregation

---

README.md

commons-60 Update readme

---

pom.xml

https://github.com/AbsaOSS/commons/security/dependabot/pom.xml/com.fasterxml.jackson.core:jackson-databind/closed

Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.6.7.4

---

README.md
src/main/scala/za/co/absa/commons/s3/S3Location.scala
src/test/scala/za/co/absa/commons/s3/S3LocationSpec.scala

`S3Location` and related utils made reusable (Atum, Spline Agent).
- unit test added
- readme added

S3Location

---

README.md

commons #79 Missing README for "ConfTyped"

---

src/main/scala/za/co/absa/commons/config/ConfigurationImplicits.scala
src/test/scala/za/co/absa/commons/config/ConfigurationImplicitsSpec.scala

commons #89 Configuration utils :: add "getRequiredObject()" method

---

src/main/scala/za/co/absa/commons/config/ConfTyped.scala

commons #96 Configuration Utils :: ConfType.rootPrefix should be def

---

pom.xml
src/main/scala/za/co/absa/commons/reflect/FieldValueExtractor.scala
src/main/scala/za/co/absa/commons/reflect/ReflectionUtils.scala
src/main/scala/za/co/absa/commons/reflect/ValueExtractor.scala
src/test/java/za/co/absa/commons/reflect/JavaClassExample.java
src/test/scala/za/co/absa/commons/reflect/ReflectionUtilsSpec.scala

Fixes https://github.com/AbsaOSS/commons/issues/103

commons #103 add method extraction in java reflection fallback

---

README.md
pom.xml
src/main/scala/za/co/absa/commons/config/ConfigurationImplicits.scala
src/test/scala/za/co/absa/commons/config/ConfigurationImplicitsSpec.scala

commons #109 add toMap method for ConfigurationImplicits

---

src/main/scala/za/co/absa/commons/io/TempDirectory.scala
src/main/scala/za/co/absa/commons/io/TempFile.scala
src/test/scala/za/co/absa/commons/io/TempDirectorySpec.scala
src/test/scala/za/co/absa/commons/io/TempFileSpec.scala

- added `toString` and `toURI` methods
Closes #117

#117 - extend TempFile and TempDirectory class

---

README.md
src/main/scala/za/co/absa/commons/io/TempDirectory.scala
src/main/scala/za/co/absa/commons/io/TempFile.scala
src/test/scala/za/co/absa/commons/io/TempDirectorySpec.scala
src/test/scala/za/co/absa/commons/io/TempFileSpec.scala

- rename toString to asString
- update README file
- udpate in unit tests
Closes #120

#120 - Refactoring toString to asString

---

README.md
src/main/scala/za/co/absa/commons/lang/extensions/NonOptionExtension.scala
src/main/scala/za/co/absa/commons/lang/extensions/TraversableExtension.scala
src/test/scala/za/co/absa/commons/lang/extensions/TraversableExtensionSpec.scala

commons #123 add toOption and toNonEmptyOption methods, deprecate asOption

---

.github/workflows/check-jacoco.yml
README.md
pom.xml

- Added support for code coverage GitHub action check as part of PR.
- Used Absa fork of JaCoCo solution - with scala method filtering.
Closes #126

#126 - Add code coverage support improve

---

README.md
src/main/scala/za/co/absa/commons/s3/S3Location.scala
src/test/scala/za/co/absa/commons/s3/S3LocationSpec.scala

Closes #129 
This is from our internal project Ursa-Unify.

#129: adding functions that ensure that S3 locations ends/doesn't end with '/'

---

pom.xml

fixes #128 
- Add  the `root-pom` as a parent
- Remove relevant portion of this pom that is inherited from the root.

commons #128 Inherit from root-pom
